import os
import sys
from pathlib import Path

# Import the actual classes from your project
from src.bootstrap.codebase_reader import CodebaseReader
from src.bootstrap.bootstrap_runner import BootstrapRunner

def main():
    print("=" * 80)
    print("Testing CodebaseReader and BootstrapRunner with Real LLM")
    print("=" * 80)

    # -------------------------------------------------------------------------
    # STEP 1: Define the path to your codebase
    # -------------------------------------------------------------------------
    # Replace this string with the absolute path to your target codebase.
    # For example: r"C:\Users\YourName\Projects\MyApp"
    # Using "." means it will read the current directory (D:\Code\Test)
    # target_codebase = r"D:\Code\Ad_bi" 
    target_codebase = r"D:\Code\pureLane"

    target_path = Path(target_codebase).resolve()
    if not target_path.exists() or not target_path.is_dir():
        print(f"❌ Error: The path {target_path} does not exist or is not a directory.")
        sys.exit(1)

    print(f"\n[Step 1] Reading codebase at: {target_path}")
    
    # Initialize the reader. You can increase token_budget if your LLM supports it (e.g., 8000 or 16000)
    reader = CodebaseReader(token_budget=8000)
    
    # Read the codebase files
    payload = reader.read(str(target_path))
    
    print(f"  ✓ Successfully read {len(payload.file_contents)} files")
    print(f"  ✓ Files skipped (budget/ignore): {len(payload.files_skipped)}")
    print(f"  ✓ Detected stack: {', '.join(payload.detected_stack)}")
    print(f"  ✓ Token budget used: {payload.total_tokens_used} / {reader.token_budget}")


    # -------------------------------------------------------------------------
    # STEP 2: Run BootstrapRunner with Real LLM (use_mock=False)
    # -------------------------------------------------------------------------
    print("\n[Step 2] Sending codebase to LLM for inference...")
    print("  (This might take a minute depending on your LM Studio model speed)")
    
    runner = BootstrapRunner()
    
    # Provide a sample change request or task that you want the LLM to analyze the codebase for
    change_request = "Analyze this codebase and tell me its main purpose."
    
    try:
        # Crucial part: use_mock=False forces it to use the real LLM endpoint
        result = runner.infer(payload, change_request, use_mock=False)
        
        print("\n✅ Inference Complete! LLM Response:\n")
        print("-" * 80)
        
        # Print the draft context generated by the LLM
        print(result.draft_context_md)
        print("-" * 80)
        
        # Print any unknowns/questions the LLM generated
        if result.unknown_entries:
            print(f"\n❓ The LLM asked {len(result.unknown_entries)} clarifying questions:")
            for i, question in enumerate(result.unknown_entries, 1):
                print(f"  {i}. {question}")
        else:
            print("\n✓ The LLM generated the context without any [UNKNOWN] questions.")
            
    except Exception as e:
        print(f"\n❌ Inference failed. Make sure LM Studio is running and the API is accessible.")
        print(f"Error details: {e}")

if __name__ == "__main__":
    main()
